version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: >
      bash -c "if [ -e tmp/pids/server.pid ]; then rm tmp/pids/server.pid ;fi && foreman start"
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - .:/book_recorder
      - ./tmp/share:/share
      - ./tmp/mysql:/var/lib/mysql
    depends_on:
      - db
    links:
      - db
      - db:database
      - db:mysql
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./tmp/share:/share
      - ./tmp/mysql:/var/lib/mysql
    env_file: ./docker/db/.mysql_env
  redis:
    image: redis
